# Generated by Django 4.1.7 on 2023-03-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_criticsregister_aspirantsregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirantsregister',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criticsregister',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
