# Generated by Django 4.1.7 on 2023-03-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aspirantsregister_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspirantsregister',
            old_name='userid',
            new_name='aspid',
        ),
        migrations.RenameField(
            model_name='criticsregister',
            old_name='userid',
            new_name='critid',
        ),
    ]
