# Generated by Django 4.1.7 on 2023-03-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_addmovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmovies',
            name='movid',
        ),
    ]
