# Generated by Django 4.1.7 on 2023-03-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_addvideos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvideos',
            name='image',
        ),
        migrations.AddField(
            model_name='addvideos',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
