# Generated by Django 4.1.7 on 2023-03-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_addvideos_image_addvideos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvideos',
            name='aspid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
