# Generated by Django 4.1.7 on 2023-03-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_addvideos_aspid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvideos',
            name='duration',
        ),
    ]
