# Generated by Django 4.1.7 on 2023-03-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_addvideos_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critid', models.CharField(max_length=100, null=True)),
                ('moviename', models.CharField(max_length=100, null=True)),
                ('comment', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
