# Generated by Django 4.1.7 on 2023-03-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_addreview_critid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addreview',
            new_name='Addmoviereview',
        ),
        migrations.CreateModel(
            name='Addvideoreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100, null=True)),
                ('comment', models.FileField(null=True, upload_to='')),
                ('critid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.criticsregister')),
            ],
        ),
    ]
