# Generated by Django 4.1.7 on 2023-03-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_addreview_addmoviereview_addvideoreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvideoreview',
            old_name='critid',
            new_name='aspid',
        ),
        migrations.RenameField(
            model_name='addvideoreview',
            old_name='moviename',
            new_name='videoname',
        ),
    ]
