# Generated by Django 4.1.7 on 2023-03-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_critid_addvideoreview_aspid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvideoreview',
            old_name='aspid',
            new_name='critid',
        ),
    ]
