# Generated by Django 4.1.7 on 2023-03-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_addvideoreview_replay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messageuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.FileField(null=True, upload_to='')),
                ('replay', models.FileField(null=True, upload_to='')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userregister')),
            ],
        ),
    ]
