# Generated by Django 4.1.7 on 2023-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_messageuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageuser',
            name='aspid',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
