# Generated by Django 4.1.7 on 2023-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_messageuser_aspid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoviereview',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addvideoreview',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addvideoreview',
            name='replay',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messageuser',
            name='aspid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messageuser',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messageuser',
            name='replay',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
