# Generated by Django 4.1.7 on 2023-03-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_like_movieid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='movieid',
            new_name='mid',
        ),
    ]
