# Generated by Django 4.1.7 on 2023-03-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_movieid_like_mid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
    ]
