# Generated by Django 4.1.7 on 2023-03-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_like_dislike_remove_like_like_like_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovies',
            name='dislikes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='likes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
