# Generated by Django 4.1.7 on 2023-03-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_addmovies_dislikes_addmovies_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmovies',
            name='dislikes',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addmovies',
            name='likes',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
