# Generated by Django 4.1.7 on 2023-03-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_addmovies_dislikes_alter_addmovies_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmovies',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
