# Generated by Django 4.1.7 on 2023-03-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_addmovies_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvideos',
            name='dislikes',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addvideos',
            name='likes',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
