# Generated by Django 4.1.7 on 2023-03-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_addvideos_dislikes_addvideos_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='videolike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='none', max_length=100, null=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userregister')),
                ('vid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.addmovies')),
            ],
        ),
    ]
