# Generated by Django 4.1.7 on 2023-03-22 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_videolike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolike',
            name='vid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.addvideos'),
        ),
    ]
