# Generated by Django 4.1.7 on 2023-03-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_videolike_vid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='userid',
            new_name='aspid',
        ),
        migrations.RenameField(
            model_name='videolike',
            old_name='userid',
            new_name='aspid',
        ),
    ]
