# Generated by Django 4.1.7 on 2023-03-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_userid_like_aspid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='aspid',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='aspid',
        ),
        migrations.AddField(
            model_name='like',
            name='critid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.criticsregister'),
        ),
        migrations.AddField(
            model_name='videolike',
            name='critid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.criticsregister'),
        ),
    ]
