# Generated by Django 4.1.3 on 2023-04-15 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_like_aspid_remove_videolike_aspid_like_critid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useraddvideoreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('replay', models.CharField(max_length=100, null=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userregister')),
            ],
        ),
    ]
