# Generated by Django 4.1.3 on 2023-04-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_useraddvideoreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvideos',
            name='aspid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aspirantsregister'),
        ),
    ]
