# Generated by Django 4.1.3 on 2023-04-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_like_type_alter_videolike_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useraddmoviereview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userregister')),
            ],
        ),
    ]
