# Generated by Django 4.1.3 on 2023-04-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_useraddmoviereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvideoreview',
            old_name='comment',
            new_name='pdf',
        ),
    ]
