# Generated by Django 4.1.3 on 2023-04-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_uservideolike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmovies',
            name='dislikes',
            field=models.IntegerField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addmovies',
            name='likes',
            field=models.IntegerField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addvideos',
            name='dislikes',
            field=models.IntegerField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addvideos',
            name='likes',
            field=models.IntegerField(default='0', max_length=100, null=True),
        ),
    ]
